server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # 1) NGINX
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: firstgamble
          env: prod
          service: nginx
          __path__: /var/log/nginx/*.log

  # 2) JOURNALD (systemd) — API, бот и всё остальное
  - job_name: journald
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: firstgamble
        env: prod
    relabel_configs:
      - source_labels: ['__journal__hostname']
        target_label: host

      - source_labels: ['__journal__systemd_unit']
        target_label: unit

      - source_labels: ['__journal__syslog_identifier']
        target_label: service

      # отсекаем шум systemd, если не нужен
      - source_labels: ['unit']
        regex: 'systemd.*'
        action: drop
